version: '3'
networks:
  our_net:
    driver: bridge
services:
  spark-master:
    image: bde2020/spark-master:3.2.0-hadoop3.2
    container_name: spark-master
    networks:
      - our_net
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
  spark-worker-1:
    image: bde2020/spark-worker:3.2.0-hadoop3.2
    container_name: spark-worker-1
    networks:
      - our_net
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
  pyspark:
    image: jupyter/all-spark-notebook:notebook-6.4.12
    container_name: jupyter-spark
    #volumes:
    #  - ./pyspark-data:/home/jovyan
    networks:
      - our_net
    ports:
      - 8888:8888
